2025-09-06 20:49:19,535 ERROR: Exception on /login [GET] [in D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\routes.py", line 95, in login
    return render_template("login.html", title=_("Sign In"), form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2025-09-06 20:49:19,535 ERROR: Exception on /login [GET] [in D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\routes.py", line 95, in login
    return render_template("login.html", title=_("Sign In"), form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2025-09-06 20:49:55,048 INFO: Microblog startup [in D:\Programmieren\Python\Flask\Tutorials\microblog\app\__init__.py:65]
2025-09-06 20:49:55,106 INFO: Microblog startup [in D:\Programmieren\Python\Flask\Tutorials\microblog\app\__init__.py:105]
2025-09-06 20:49:55,106 INFO: Microblog startup [in D:\Programmieren\Python\Flask\Tutorials\microblog\app\__init__.py:105]
2025-09-06 20:49:58,798 ERROR: Exception on /login [GET] [in D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\routes.py", line 95, in login
    return render_template("login.html", title=_("Sign In"), form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2025-09-06 20:49:58,798 ERROR: Exception on /login [GET] [in D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\routes.py", line 95, in login
    return render_template("login.html", title=_("Sign In"), form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2025-09-06 20:50:00,420 ERROR: Exception on /login [GET] [in D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\routes.py", line 95, in login
    return render_template("login.html", title=_("Sign In"), form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programmieren\Python\Flask\Tutorials\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
